### ISSUE TITLE
it not work

### ISSUE THREAD

**Issue by hapic** [sripathikrishnan/redis-rdb-tools#104]
run  'rdb  -c memory dump.rdb > /tmp/redis_memory_report_1012.csv'
it show :  
Traceback (most recent call last):
  File "/usr/local/python27/bin/rdb", line 11, in <module>
    load_entry_point('rdbtools==0.1.11', 'console_scripts', 'rdb')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2630, in load_entry_point
ImportError: Entry point ('console_scripts', 'rdb') not found
i don't konw how to do.
my python 
Python 2.7.11

Thanks

**Comment by oranagra** [comment]
it works for me.
i guess it's some local problem on your computer.
when you solve it, if you reach a conclusion that rdb-tools can be improved, please post a solution.

**Comment by yangyifei93** [comment]
same problem

Traceback (most recent call last):
  File "/usr/bin/rdb", line 11, in <module>
    load_entry_point('rdbtools==0.1.12', 'console_scripts', 'rdb')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2713, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'rdb') not found

Python 2.7.5
