### ISSUE TITLE
TypeError: object of type 'long' has no len()

### ISSUE THREAD

**Issue by tempuser14** [sripathikrishnan/redis-rdb-tools#106]
I have installed redis-rdb-tools in Cygwin and on running `rdb -c memory dump.rdb_redis02 --bytes 128 -f memory_02.csv` I get:

> Traceback (most recent call last):
  File "/usr/bin/rdb", line 11, in <module>
    load_entry_point('rdbtools==0.1.11', 'console_scripts', 'rdb')()
  File "/usr/lib/python2.7/site-packages/rdbtools/cli/rdb.py", line 86, in main
    parser.parse(dump_file)
  File "/usr/lib/python2.7/site-packages/rdbtools/parser.py", line 326, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/lib/python2.7/site-packages/rdbtools/parser.py", line 379, in parse_fd
    self.read_object(f, data_type)
  File "/usr/lib/python2.7/site-packages/rdbtools/parser.py", line 498, in read_object
    self.read_hash_from_ziplist(f)
  File "/usr/lib/python2.7/site-packages/rdbtools/parser.py", line 659, in read_hash_from_ziplist
    self._callback.hset(self._key, field, value)
  File "/usr/lib/python2.7/site-packages/rdbtools/memprofiler.py", line 207, in hset
    if(element_length(value) > self._len_largest_element) :
  File "/usr/lib/python2.7/site-packages/rdbtools/memprofiler.py", line 489, in element_length
    return len(element)
TypeError: object of type 'long' has no len()

Any ideas on the cause? Can it be python version (2.7)?

**Comment by oranagra** [comment]
@mihu this looks like a regression from https://github.com/sripathikrishnan/redis-rdb-tools/commit/d7965253799df9850b27a8c8106e89c303041e15
can you take a look, do you recall what was the reason you wanted to remove the dependency of long?

**Comment by oranagra** [comment]
fix released in version 0.1.12.
thanks for reporting
