### ISSUE TITLE
Not able to run rdb

### ISSUE THREAD

**Issue by farhad-tarapore** [sripathikrishnan/redis-rdb-tools#114]
Getting an error:

rdb -c memory dump.rdb --bytes 128 -f memory.csv
Traceback (most recent call last):
  File "/usr/bin/rdb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: redis

**Comment by oranagra** [comment]
Hi, i haven't seen that problem before.
Is your python installation healthy? do other packages work?
Can you try upgrading to python2.7?

**Comment by farhad-tarapore** [comment]
It worked with a fork of this code for Redis 3.x

**Comment by oranagra** [comment]
@farhad-tarapore do you mean to say it's a regression?
do you have a release version or commit SHA which this fork is based on?
can you please test python2.7?
can you try to narrow down the change that caused this regression?
