### ISSUE TITLE
rdb -c memory , Throw an exception: "pkg_resources.DistributionNotFound: redis"

### ISSUE THREAD

**Issue by andylee2020888** [sripathikrishnan/redis-rdb-tools#168]
python 2.7
rdbtools 0.1.15

rdb -c memory redis.rdb --bytes 128 -f redis.csv

Throw an exception:
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2603, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: redis

**Comment by bearAss13** [comment]
pip install redis

**Comment by id-id-id** [comment]
I have the same question, but i have installed redis. my redis is 5.0.6
