### ISSUE TITLE
Redis 7 Support

### ISSUE THREAD

**Issue by ronaldpetty** [sripathikrishnan/redis-rdb-tools#185]
Hello, I just gave the rdb tool a try against an RDB file from Redis 7 rc 2.

```
~/replication$ rdb --command diff ./master/dump.rdb
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 11, in <module>
    load_entry_point('rdbtools==0.1.15', 'console_scripts', 'rdb')()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rdbtools/cli/rdb.py", line 106, in main
    parser.parse(options.dump_file[0])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rdbtools/parser.py", line 394, in parse
    self.parse_fd(open(filename, "rb"))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rdbtools/parser.py", line 399, in parse_fd
    self.verify_version(f.read(4))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rdbtools/parser.py", line 963, in verify_version
    raise Exception('verify_version', 'Invalid RDB version number %d' % version)
Exception: ('verify_version', 'Invalid RDB version number 10')
```

Just for giggles, I changed the 10 to a 09 and it seems to work (at least diffing).

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ronaldpetty** [comment]
别客气

https://github.com/sripathikrishnan/redis-rdb-tools/pull/186

**Comment by madolson** [comment]
It should mostly work, there are a couple of new RDB op codes like functions that need to be supported.

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rhuddleston** [comment]
on upgrade Hash types are auto-converted RDB_TYPE_HASH -> RDB_TYPE_HASH_LISTPACK so at a minimum rdb-tools will need to be upgraded to understand how to decode HASH_LISTPACK objects.

https://github.com/redis/redis/pull/8887

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~
