### ISSUE TITLE
Invalid RDB version number 10

### ISSUE THREAD

**Issue by JStyle21** [sripathikrishnan/redis-rdb-tools#187]
Hi,

Is version 10 not supported?

```
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/rdbtools/cli/rdb.py", line 106, in main
    parser.parse(options.dump_file[0])
  File "/usr/local/lib/python3.8/dist-packages/rdbtools/parser.py", line 394, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/local/lib/python3.8/dist-packages/rdbtools/parser.py", line 399, in parse_fd
    self.verify_version(f.read(4))
  File "/usr/local/lib/python3.8/dist-packages/rdbtools/parser.py", line 963, in verify_version
    raise Exception('verify_version', 'Invalid RDB version number %d' % version)
Exception: ('verify_version', 'Invalid RDB version number 10')

```

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by emahdij** [comment]
I had the same problem. In the end, I used another [tool](https://github.com/leonchen83/redis-rdb-cli) and it works now.

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JStyle21** [comment]
> I had the same problem. In the end, I used another [tool](https://github.com/leonchen83/redis-rdb-cli) and it works now.

Thank you i will try it

**Comment by rahulbansal-testbook** [comment]
Any updates?

**Comment by kollein** [comment]
> I had the same problem. In the end, I used another [tool](https://github.com/leonchen83/redis-rdb-cli) and it works now.
Thanks @emahdij 
It works well for the version number 10.

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JStyle21** [comment]
> > I had the same problem. In the end, I used another [tool](https://github.com/leonchen83/redis-rdb-cli) and it works now.
> 
> Thank you i will try it

Just to update, i tried the mentioned project but it's not the same, i wanted a simple client not a set of tools.
Maybe it's me but i couldn't figure out how to use it at the time, i solved my issue using Docker.

But now i just wanted to update that i've switched to using this [tool](https://github.com/IBM-Cloud/redli) instead which works like a charm, updated and has binary releases on all platforms.

I"m keeping the ticket open since it's for this project and it hasn't been fixed here.

**Comment by josduj** [comment]
I ended up just manually editing this line to not throw on version 10 and it works perfectly fine (at least for my simple use case)
https://github.com/sripathikrishnan/redis-rdb-tools/blob/548b11ec3c81a603f5b321228d07a61a0b940159/rdbtools/parser.py#L962

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~
