### ISSUE TITLE
redis-memory-for-key not work for redis cluster

### ISSUE THREAD

**Issue by awaken233** [sripathikrishnan/redis-rdb-tools#190]
Traceback (most recent call last):
  File "/opt/homebrew/bin/redis-memory-for-key", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/rdbtools/cli/redis_memory_for_key.py", line 42, in main
    print_memory_for_key(redis_key, host=options.host, port=options.port,
  File "/opt/homebrew/lib/python3.10/site-packages/rdbtools/cli/redis_memory_for_key.py", line 53, in print_memory_for_key
    raw_dump = redis.execute_command('dump', key)
  File "/Users/evtok/Library/Python/3.10/lib/python/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/evtok/Library/Python/3.10/lib/python/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/evtok/Library/Python/3.10/lib/python/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MOVED 8829 192.168.18.172:6379

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~
