### ISSUE TITLE
datetime.datetime.utcfromtimestamp

### ISSUE THREAD

**Issue by guaguaguaxia** [sripathikrishnan/redis-rdb-tools#195]
PS C:\python311\lib\site-packages\rdbtools\cli> python rdb.py -c memory C:\Users\guagu\Desktop\redis_rdb\hins25205082_data_20231208042425.rdb --bytes 128 -f memory.csv
Traceback (most recent call last):
  File "C:\python311\lib\site-packages\rdbtools\cli\rdb.py", line 112, in <module>
    main()
  File "C:\python311\lib\site-packages\rdbtools\cli\rdb.py", line 106, in main
    parser.parse(options.dump_file[0])
  File "C:\Python311\Lib\site-packages\rdbtools\parser.py", line 394, in parse
    self.parse_fd(open(filename, "rb"))
  File "C:\Python311\Lib\site-packages\rdbtools\parser.py", line 411, in parse_fd
    self._expiry = read_milliseconds_time(f)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rdbtools\parser.py", line 1104, in read_milliseconds_time
    return to_datetime(read_unsigned_long(f) * 1000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rdbtools\parser.py", line 1067, in to_datetime
    dt = datetime.datetime.utcfromtimestamp(seconds_since_epoch)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

![1702021444341](https://github.com/sripathikrishnan/redis-rdb-tools/assets/18466048/05d17179-8eae-49c7-b296-7cc142554004)

I had this problem use this command.please help me

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~
