### ISSUE TITLE
This tool does not support redis 7 version rdb file parsing

### ISSUE THREAD

**Issue by aolixingo** [sripathikrishnan/redis-rdb-tools#202]
This tool does not support redis 7 version rdb file parsing
The error is as follows:
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 33, in <module>
    sys.exit(load_entry_point('rdbtools==0.1.15', 'console_scripts', 'rdb')())
  File "/Library/Python/3.9/site-packages/rdbtools-0.1.15-py3.9.egg/rdbtools/cli/rdb.py", line 106, in main
  File "/Library/Python/3.9/site-packages/rdbtools-0.1.15-py3.9.egg/rdbtools/parser.py", line 394, in parse
  File "/Library/Python/3.9/site-packages/rdbtools-0.1.15-py3.9.egg/rdbtools/parser.py", line 399, in parse_fd
  File "/Library/Python/3.9/site-packages/rdbtools-0.1.15-py3.9.egg/rdbtools/parser.py", line 963, in verify_version
Exception: ('verify_version', 'Invalid RDB version number 10')

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuanzhi201111** [comment]
我也遇到这工具无法解析redis 7的问题，有办法解决吗

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~

**Comment by ChenWei-XiaoYi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 919927181** [comment]
[/919927181/rdr](https://github.com/919927181/rdr)  基于 [xueqiu/rdr](https://github.com/xueqiu/rdr)（rdr 基于redis-rdb-tools） golang开发，支持了redis7+。

**Comment by smilyFw** [comment]
您好，我已收到您的邮件，谢谢！！~~
