### ISSUE TITLE
ValueError: year is out of range

### ISSUE THREAD

**Issue by brianantonelli** [sripathikrishnan/redis-rdb-tools#28]
I'm trying to dump my RDB to a JSON file filtered by a particular key. I get an error (ValueError: year is out of range) regardless of the key filter being applied. I'm running Python 2.7.1 on OSX 10.7.5

```
rdb --command json --key "user.*" dump.rdb
```

Error:

```
[{Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 8, in <module>
    load_entry_point('rdbtools==0.1.5', 'console_scripts', 'rdb')()
  File "/Library/Python/2.7/site-packages/rdbtools-0.1.5-py2.7.egg/rdbtools/cli/rdb.py", line 79, in main
    parser.parse(dump_file)
  File "/Library/Python/2.7/site-packages/rdbtools-0.1.5-py2.7.egg/rdbtools/parser.py", line 284, in parse
    self._expiry = to_datetime(read_unsigned_long(f) * 1000)
  File "/Library/Python/2.7/site-packages/rdbtools-0.1.5-py2.7.egg/rdbtools/parser.py", line 705, in to_datetime
    dt = datetime.datetime.utcfromtimestamp(seconds_since_epoch)
ValueError: year is out of range
```

**Comment by oranagra** [comment]
this was already fixed by 3470263b725ce651894f1331bed8133f261a42fc (already included in v 0.1.9)
