### ISSUE TITLE
Converting rdb to protocol

### ISSUE THREAD

**Issue by mabdullah353** [sripathikrishnan/redis-rdb-tools#69]
`Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.6', 'console_scripts', 'rdb')()
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/cli/rdb.py", line 82, in main
    parser.parse(dump_file)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 306, in parse
    self.read_object(f, data_type)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 389, in read_object
    score = float(score)
ValueError: invalid literal for float(): 8US-08-554690:G:3647.07874343085132US-07-495050:G`

**Comment by mihu** [comment]
Could you please try the latest 0.1.7?
