### ISSUE TITLE
Throwing error when encoding None key 

### ISSUE THREAD

**Issue by heera-jaiswal** [sripathikrishnan/redis-rdb-tools#72]
It seems None(null) key is not handled while encoding
**Error Trace**
`Traceback (most recent call last):
  File "bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.7', 'console_scripts', 'rdb')()
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/cli/rdb.py", line 82, in main
    parser.parse(dump_file)
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 293, in parse
    self.parse_fd(open(filename, "rb"))
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 337, in parse_fd
    self._callback.end_database(db_number)
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/memprofiler.py", line 131, in end_database
    self._stream.next_record(record)
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/memprofiler.py", line 82, in next_record
    self._out.write("%d,%s,%s,%d,%s,%d,%d\n" % (record.database, record.type, encode_key(record.key),
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 92, in encode_key
    return _encode(s, quote_numbers=True)
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 89, in _encode
    return _encode_basestring_ascii(s)
  File "/home/ec2-user/python-benchmark/env/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 70, in _encode_basestring_ascii
    return '"' + str(ESCAPE_ASCII.sub(replace, s)) + '"'
TypeError: expected string or buffer`

I have printed actual record throwing this error
`MemoryRecord(database=0, type='dict', key=None, bytes=104.0, encoding=None, size=None, len_largest_element=None)`

RDB file is hereby attached.
[dump.zip](https://github.com/sripathikrishnan/redis-rdb-tools/files/519026/dump.zip)

**Comment by oranagra** [comment]
@heera-jaiswal this was actually already resolved (see issue #70), but i haven't released a new version till now.
please check version 0.1.8.
thanks.
