### ISSUE TITLE
Converting rdb to protocol (UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5)

### ISSUE THREAD

**Issue by mvreg** [sripathikrishnan/redis-rdb-tools#75]
uporabnik@lju2134:~$ rdb --command protocol dump-redis-6401.rdb
*2
$6
SELECT
$1
0
*3
$3
SET
$37
pb-urn:sspcreativeapprovalstatus:6741
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.8', 'console_scripts', 'rdb')()
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/cli/rdb.py", line 82, in main
    parser.parse(dump_file)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 293, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 346, in parse_fd
    self.read_object(f, data_type)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 401, in read_object
    self._callback.set(self._key, val, self._expiry, info={'encoding':'string'})
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 310, in set
    self.emit('SET', key, value)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 299, in emit
    self._out.write(u"$" + unicode(len(unicode(arg))) + u"\r\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 1: ordinal not in range(128)

version used: 
sudo pip install git+https://github.com/sripathikrishnan/redis-rdb-tools@28ccd5b5dec0ac6e8724af3c61d167771b4d9c77  --upgrade

**Comment by oranagra** [comment]
fixed by #77
