### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 264: ordinal not in range(128)

### ISSUE THREAD

**Issue by coin8086** [sripathikrishnan/redis-rdb-tools#81]
rdb --command protocol dump.rdb 
...
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 9, in <module>
    load_entry_point('rdbtools==0.1.8', 'console_scripts', 'rdb')()
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/cli/rdb.py", line 82, in main
    parser.parse(dump_file)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 293, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 346, in parse_fd
    self.read_object(f, data_type)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 401, in read_object
    self._callback.set(self._key, val, self._expiry, info={'encoding':'string'})
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 310, in set
    self.emit('SET', key, value)
  File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 299, in emit
    self._out.write(u"$" + unicode(len(unicode(arg))) + u"\r\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 264: ordinal not in range(128)

My OS is Ubuntu 14.04.4 64 bits.

I saw a few similar issues like this https://github.com/sripathikrishnan/redis-rdb-tools/issues/75 and you said it's fixed but seems not: unicode() is still there and I don't see str() to replace it. Maybe you fixed in code but not in distributed package yet? Or I installed the stale version? I installed it by "pip install ..." as README said.

Thanks.

**Comment by amotzg** [comment]
@coin8086 It is indeed fixed on master but not released as a version yet.
To use most recent code, you can install master code from source using `setup.py`. As in the second README described method.
Note that master code is not considered stable yet, and may contain some fix that have not been tested enough.

**Comment by coin8086** [comment]
@amotzg OK, I'm now using the code on master and it works. Anyway it would be good to make the fix in a release soon so that others wouldn't get confused as I did, or at least make some notes in README.
