### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by aligajani** [sripathikrishnan/redis-rdb-tools#85]
```
  Using cached rdbtools-0.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/fj/d9k5_d914m51bd5_8f0s92bh0000gn/T/pip-build-gmjvsvbw/rdbtools/setup.py", line 3, in <module>
        from rdbtools import __version__
      File "/private/var/folders/fj/d9k5_d914m51bd5_8f0s92bh0000gn/T/pip-build-gmjvsvbw/rdbtools/rdbtools/__init__.py", line 2, in <module>
        from rdbtools.callbacks import JSONCallback, DiffCallback, ProtocolCallback

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fj/d9k5_d914m51bd5_8f0s92bh0000gn/T/pip-build-gmjvsvbw/rdbtools
```

**Comment by aligajani** [comment]
@sripathikrishnan

**Comment by oranagra** [comment]
@aligajani i tested it a few times and everything seems ok.
can you tell me more about your environment? python version, or any other detail?
does the output contain any other information? (it seems partial)
also, i just released a new version (0.1.9 into pypi), can you please re-test?
