### ISSUE TITLE
Unicode error in conversion to protocol

### ISSUE THREAD

**Issue by miketheman** [sripathikrishnan/redis-rdb-tools#87]
In rdbtools 0.1.7, 0.1.8, triggering the following traceback (couldn't try 0.1.9 due to #86):

```
Traceback (most recent call last):
  File "/usr/local/bin/rdb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/rdbtools/cli/rdb.py", line 67, in main
    parser.parse(dump_file)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 293, in parse
    self.parse_fd(open(filename, "rb"))
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 346, in parse_fd
    self.read_object(f, data_type)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 451, in read_object
    self.read_hash_from_ziplist(f)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/parser.py", line 597, in read_hash_from_ziplist
    self._callback.hset(self._key, field, value)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/callbacks.py", line 319, in hset
    self.emit('HSET', key, field, value)
  File "/usr/local/lib/python2.7/site-packages/rdbtools/callbacks.py", line 299, in emit
    self._out.write(u"$" + unicode(len(unicode(arg))) + u"\r\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

The key in question looks like:

```json
"users:id:U2":{"name":"Gr\u00e4\u00dfl"}
```

**Comment by amotzg** [comment]
@miketheman, @oranagra, this error is fixed in 0.1.9.
